# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SimpleWin.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SimpleWindow(object):
    def setupUi(self, SimpleWindow):
        SimpleWindow.setObjectName("SimpleWindow")
        SimpleWindow.resize(844, 595)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        SimpleWindow.setFont(font)
        SimpleWindow.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.centralwidget = QtWidgets.QWidget(SimpleWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser_left = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_left.setGeometry(QtCore.QRect(70, 120, 200, 171))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(100)
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser_left.setFont(font)
        self.textBrowser_left.setObjectName("textBrowser_left")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setGeometry(QtCore.QRect(360, 30, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.textBrowser_right = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_right.setGeometry(QtCore.QRect(380, 120, 200, 171))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(100)
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser_right.setFont(font)
        self.textBrowser_right.setObjectName("textBrowser_right")
        self.pbt_start1 = QtWidgets.QPushButton(self.centralwidget)
        self.pbt_start1.setGeometry(QtCore.QRect(120, 500, 121, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pbt_start1.setFont(font)
        self.pbt_start1.setObjectName("pbt_start1")
        self.label_tip1 = QtWidgets.QLabel(self.centralwidget)
        self.label_tip1.setGeometry(QtCore.QRect(50, 340, 731, 61))
        self.label_tip1.setMinimumSize(QtCore.QSize(271, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_tip1.setFont(font)
        self.label_tip1.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_tip1.setTextFormat(QtCore.Qt.PlainText)
        self.label_tip1.setWordWrap(True)
        self.label_tip1.setObjectName("label_tip1")
        self.label_tips = QtWidgets.QLabel(self.centralwidget)
        self.label_tips.setGeometry(QtCore.QRect(30, 300, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_tips.setFont(font)
        self.label_tips.setObjectName("label_tips")
        self.pbt_back1 = QtWidgets.QPushButton(self.centralwidget)
        self.pbt_back1.setGeometry(QtCore.QRect(590, 500, 121, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pbt_back1.setFont(font)
        self.pbt_back1.setObjectName("pbt_back1")
        self.pbt_over1 = QtWidgets.QPushButton(self.centralwidget)
        self.pbt_over1.setGeometry(QtCore.QRect(360, 500, 121, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pbt_over1.setFont(font)
        self.pbt_over1.setObjectName("pbt_over1")
        self.label_tip1_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_tip1_2.setGeometry(QtCore.QRect(90, 390, 731, 61))
        self.label_tip1_2.setMinimumSize(QtCore.QSize(271, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_tip1_2.setFont(font)
        self.label_tip1_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_tip1_2.setTextFormat(QtCore.Qt.PlainText)
        self.label_tip1_2.setWordWrap(True)
        self.label_tip1_2.setObjectName("label_tip1_2")
        self.label_tip1_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_tip1_3.setGeometry(QtCore.QRect(700, 120, 271, 41))
        self.label_tip1_3.setMinimumSize(QtCore.QSize(271, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_tip1_3.setFont(font)
        self.label_tip1_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_tip1_3.setTextFormat(QtCore.Qt.PlainText)
        self.label_tip1_3.setWordWrap(True)
        self.label_tip1_3.setObjectName("label_tip1_3")
        self.label_tip1_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_tip1_4.setGeometry(QtCore.QRect(90, 440, 731, 61))
        self.label_tip1_4.setMinimumSize(QtCore.QSize(271, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_tip1_4.setFont(font)
        self.label_tip1_4.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_tip1_4.setTextFormat(QtCore.Qt.PlainText)
        self.label_tip1_4.setWordWrap(True)
        self.label_tip1_4.setObjectName("label_tip1_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(310, 180, 81, 61))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(610, 180, 81, 61))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(660, 180, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.lineEdit.setFont(font)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        SimpleWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(SimpleWindow)
        QtCore.QMetaObject.connectSlotsByName(SimpleWindow)

    def retranslateUi(self, SimpleWindow):
        _translate = QtCore.QCoreApplication.translate
        SimpleWindow.setWindowTitle(_translate("SimpleWindow", "MainWindow"))
        self.label_title.setText(_translate("SimpleWindow", "简单测试"))
        self.textBrowser_right.setHtml(_translate("SimpleWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:100pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:80pt;\"><br /></p></body></html>"))
        self.pbt_start1.setText(_translate("SimpleWindow", "开始测试"))
        self.label_tip1.setText(_translate("SimpleWindow", "    1.数字出现的频率是20次/分钟，每组的两个数字显示的间隔时间是0.5秒。"))
        self.label_tips.setText(_translate("SimpleWindow", "注意："))
        self.pbt_back1.setText(_translate("SimpleWindow", "返回主界面"))
        self.pbt_over1.setText(_translate("SimpleWindow", "结束测试"))
        self.label_tip1_2.setText(_translate("SimpleWindow", "2.点击【开始测试】按钮，开始测试，3秒后出现第一组数字，请您做好准备。"))
        self.label_tip1_3.setText(_translate("SimpleWindow", "输入框"))
        self.label_tip1_4.setText(_translate("SimpleWindow", "3.点击【结束测试】按钮，测试停止，显示及输入的数字以Excel文件的形式生成。"))
        self.label.setText(_translate("SimpleWindow", "+"))
        self.label_2.setText(_translate("SimpleWindow", "="))

